# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73b539786981f1a8aee49d543c9cddb1c60227bb208ffe3100fdccc55641eb3069255a8d1f5bd00d4e76b06015ddb7a6a027faef5d2245feab5f9283befe30c2

test:
  secret_key_base: ffbc4a9833aa5140c00ef652f7a2c4b5d61e921f3bd214d6c213ecacef10378a92815c5b3ceb4863ae4426838b2222df633dd7128fd65f32d4b2781d0869fb02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
